### ISSUE TITLE
Disable Unused Code

### ISSUE THREAD

**Issue by krh6591** [Herm20/SEVENGINE#13]
There exists a large amount of unused code with linkage issues within the codebase. While technically you *can* ignore this as long as those files don't get included in your build process, it's extraordinarily poor codebase management. (Also, my automated build process (because I'm *slightly* lazy and it works as long as you don't let stuff like this happen) still includes them, as they're technically still part of the project.)

Fix, refactor out, remove, or in the very least comment out, the following problematic files :

- [ ] `Timer_Sad.h`
- [ ] `Timer_Sad.cpp`
- [ ] `InputPoller.h`
- [ ] `InputPoller.cpp`
- [x] `Scene.h`
- [x] `Scene.cpp`
- [x] `old/Entity.h`
- [x] `old/Entity.cpp`
- [x] `Components/MeshRendererComponent.h`

Additionally, for `Components/MeshRendererComponent.h`, the `MeshRendererComponent` is (albeit not in the `ecs` namespace (the only reason that even still compiles despite being very, very wrong)) already defined in `ECS/Component.h`, but this file is still referenced in `Renderer.cpp`.

- [x] Remove unused reference from `Renderer.cpp`

**Comment by SirGeoffers** [comment]
Timer_Sad.h, Timer_Sad.cpp, InputPoller.h, and InputPoller.cpp were re-enabled on the simple-character branch.  They'll be back when that is merged into master.

**Comment by SirGeoffers** [comment]
See https://github.com/Herm20/SEVENGINE/pull/17
